#!/usr/bin/env bash
set -euo pipefail

CLOUDFLARE_IPV4_URL="${CLOUDFLARE_IPV4_URL:-https://www.cloudflare.com/ips-v4}"
CLOUDFLARE_IPV6_URL="${CLOUDFLARE_IPV6_URL:-https://www.cloudflare.com/ips-v6}"

NGINX_REALIP_PATH="${CLOUDFLARE_NGINX_REALIP_PATH:-/srv/reservation-system/cloudflare/nginx-realip.conf}"

COMPOSE_ENV_FILE="${COMPOSE_ENV_FILE:-.env.production}"
COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.prod.yml}"

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  echo "This script must run as root (required for ipset/iptables)." >&2
  echo "Try: sudo bash scripts/cloudflare/update.sh" >&2
  exit 1
fi

require_command() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

fetch_lines() {
  local url="$1"
  curl -fsS --retry 3 --retry-delay 2 "$url" | sed '/^\s*#/d;/^\s*$/d'
}

require_command curl
require_command ipset
require_command iptables
require_command ip6tables
require_command sed
require_command mktemp
require_command install

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

ipv4_file="$tmpdir/ips-v4.txt"
ipv6_file="$tmpdir/ips-v6.txt"

fetch_lines "$CLOUDFLARE_IPV4_URL" >"$ipv4_file"
fetch_lines "$CLOUDFLARE_IPV6_URL" >"$ipv6_file"

if [ ! -s "$ipv4_file" ]; then
  echo "Cloudflare IPv4 list is empty; aborting to avoid locking the origin." >&2
  exit 1
fi

if [ ! -s "$ipv6_file" ]; then
  echo "Cloudflare IPv6 list is empty; aborting to avoid locking the origin." >&2
  exit 1
fi

update_ipset() {
  local set_name="$1"
  local family="$2"
  local file="$3"
  local tmp_set="${set_name}_new_$$"

  ipset create "$tmp_set" hash:net family "$family" -exist
  ipset flush "$tmp_set"

  while IFS= read -r cidr; do
    ipset add "$tmp_set" "$cidr" -exist
  done <"$file"

  ipset create "$set_name" hash:net family "$family" -exist
  ipset swap "$set_name" "$tmp_set"
  ipset destroy "$tmp_set"
}

update_ipset cloudflare4 inet "$ipv4_file"
update_ipset cloudflare6 inet6 "$ipv6_file"

supports_wait_flag() {
  local ipt="$1"
  "$ipt" -w 1 -L >/dev/null 2>&1
}

detect_base_chain() {
  local ipt="$1"

  if "$ipt" -S DOCKER-USER >/dev/null 2>&1; then
    echo "DOCKER-USER"
    return
  fi

  echo "INPUT"
}

ensure_chain() {
  local ipt="$1"
  local ipset_name="$2"
  local localhost_cidr="$3"
  local chain="CF_ORIGIN"
  local base_chain
  local -a wait_args=()

  if supports_wait_flag "$ipt"; then
    wait_args=(-w 5)
  fi

  base_chain="$(detect_base_chain "$ipt")"

  "$ipt" "${wait_args[@]}" -N "$chain" 2>/dev/null || true
  "$ipt" "${wait_args[@]}" -F "$chain"

  if [ "$base_chain" = "DOCKER-USER" ]; then
    # Allow outbound traffic FROM Docker containers (docker0, br-* compose
    # networks) so builds and containers can reach the internet on 80/443.
    "$ipt" "${wait_args[@]}" -A "$chain" -i docker0 -j RETURN
    "$ipt" "${wait_args[@]}" -A "$chain" -i br-+ -j RETURN
  fi

  "$ipt" "${wait_args[@]}" -A "$chain" -p tcp -s "$localhost_cidr" -m multiport --dports 80,443 -j ACCEPT
  "$ipt" "${wait_args[@]}" -A "$chain" -p tcp -m set --match-set "$ipset_name" src -m multiport --dports 80,443 -j ACCEPT
  "$ipt" "${wait_args[@]}" -A "$chain" -p tcp -m multiport --dports 80,443 -j DROP
  "$ipt" "${wait_args[@]}" -A "$chain" -j RETURN

  "$ipt" "${wait_args[@]}" -C "$base_chain" -p tcp -m multiport --dports 80,443 -j "$chain" 2>/dev/null \
    || "$ipt" "${wait_args[@]}" -I "$base_chain" 1 -p tcp -m multiport --dports 80,443 -j "$chain"
}

ensure_chain iptables cloudflare4 127.0.0.1/8
ensure_chain ip6tables cloudflare6 ::1/128

if command -v netfilter-persistent >/dev/null 2>&1; then
  netfilter-persistent save >/dev/null 2>&1 || true
fi

mkdir -p "$(dirname "$NGINX_REALIP_PATH")"
nginx_tmp="$tmpdir/nginx-realip.conf"

{
  echo "# Generated by scripts/cloudflare/update.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
  while IFS= read -r cidr; do
    echo "set_real_ip_from $cidr;"
  done <"$ipv4_file"
  while IFS= read -r cidr; do
    echo "set_real_ip_from $cidr;"
  done <"$ipv6_file"
} >"$nginx_tmp"

install -m 0644 "$nginx_tmp" "$NGINX_REALIP_PATH"

if command -v docker >/dev/null 2>&1; then
  if [ -f "$COMPOSE_FILE" ] && [ -f "$COMPOSE_ENV_FILE" ]; then
    if ! docker compose --env-file "$COMPOSE_ENV_FILE" -f "$COMPOSE_FILE" exec -T nginx nginx -s reload >/dev/null 2>&1; then
      echo "Warning: nginx reload failed (container may not be running yet)." >&2
    fi
  fi
fi

echo "Cloudflare allowlist updated:"
echo "- ipset: cloudflare4 / cloudflare6"
echo "- nginx real-ip conf: $NGINX_REALIP_PATH"
